[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lh_cd_project"
version = "0.1.0"
description = "Projeto LH CD"
authors = [{name="Maria Cunha"}]
